-- first remove the foreign key constraint from pups
ALTER TABLE IF EXISTS pups
  DROP COLUMN parent_id;

TRUNCATE users, pups RESTART IDENTITY CASCADE;

-- DROP the tables and constraints
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pups;

-- create the users table without the foreign key
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    user_email TEXT NOT NULL,
    user_password TEXT NOT NULL
); 

-- insert values into users
INSERT INTO users
  (user_name, user_email, user_password)
  VALUES
    ('Amber', 'amber@test.com', 'lovesdog2'),
    ('Kayla', 'kayla@test.com', 'testing123'),
    ('Crystal', 'crystal@test.com', 'testing123');


-- create the pups table
CREATE TABLE IF NOT EXISTS pups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pup_name TEXT NOT NULL,
    breed TEXT NOT NULL,
    allergies TEXT NOT NULL, 
    hobbies TEXT,
    parent_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

-- insert pups
INSERT INTO pups
  (pup_name, breed, allergies, hobbies)
  VALUES
    ('Cocoa', 'Lab', 'Peanuts', 'Plays Ball'),
    ('Bear', 'Australian Monster', 'Hoomans', 'Protecting my fortress'), 
    ('Future', 'Golden RetrievePit', 'Fake people', 'Waiting for crystal to adopt me');

-- now the parent_id relationship between users and pups is possible

ALTER TABLE pups
    ADD COLUMN parent_id INTEGER REFERENCES users(id);

-- Add parent_id to the pups
UPDATE pups SET parent_id = 1 WHERE id = 1;
UPDATE pups SET parent_id = 2 WHERE id = 2;
UPDATE pups SET parent_id = 3 WHERE id = 3;

