-- first remove the foreign key constraint from pups
ALTER TABLE IF EXISTS pups
  DROP COLUMN parent_id;

TRUNCATE users, pups, pup_services RESTART IDENTITY CASCADE;

-- DROP the tables and constraints
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS pups CASCADE;
DROP TABLE IF EXISTS pup_services CASCADE;

-- create the users table without the foreign key
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL
); 

-- insert values into users
INSERT INTO users
  (name, email, password)
  VALUES
    ('Amber', 'amber@test.com', 'lovesdog2'),
    ('Kayla', 'kayla@test.com', 'testing123'),
    ('Crystal', 'crystal@test.com', 'testing123');


-- create the pups table
CREATE TABLE IF NOT EXISTS pups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pup_name TEXT NOT NULL,
    breed TEXT NOT NULL,
    allergies TEXT, 
    hobbies TEXT,
    parent_id INTEGER REFERENCES users(id) ON DELETE CASCADE, 
    image_url TEXT
);

-- insert pups
INSERT INTO pups
  (pup_name, breed, allergies, hobbies, image_url)
  VALUES
    ('Cocoa', 'Lab', 'Peanuts', 'Plays Ball', 'https://i.pinimg.com/originals/63/45/38/634538e61eb1fae4d51c345f6b47f376.jpg'),
    ('Bear', 'Australian Monster', 'Hoomans', 'Protecting my fortress', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Redtriaussie01.jpg/440px-Redtriaussie01.jpg'), 
    ('Future', 'Golden RetrievePit', 'Fake people', 'Waiting for crystal to adopt me', 'https://upload.wikimedia.org/wikipedia/commons/9/93/Golden_Retriever_Carlos_%2810581910556%29.jpg');

-- Add parent_id to the pups
UPDATE pups SET parent_id = 1 WHERE id = 1;
UPDATE pups SET parent_id = 2 WHERE id = 2;
UPDATE pups SET parent_id = 3 WHERE id = 3;



-- CREATE PUPSEVICE table without the foreign key
CREATE TABLE IF NOT EXISTS pup_services (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    appt_date Date,
    service_type TEXT NOT NULL,
    note TEXT,
    pup_id INTEGER REFERENCES pups(id) ON DELETE CASCADE

); 

-- insert values into pup_services
INSERT INTO pup_services
  (appt_date, service_type, note)
  VALUES
    ('12/24/2019', 'Grooming', 'Loves bath time'),
    ('1/14/2020', 'Daycare', 'Hates small dogs'),
    ('2/1/2020', 'Vet', 'Update on shots');


-- Add parent_id to the pups
UPDATE pup_services SET pup_id = 1 WHERE id = 1;
UPDATE pup_services SET pup_id = 2 WHERE id = 2;
UPDATE pup_services SET pup_id = 3 WHERE id = 3;


