
  
TRUNCATE pup_services, pups RESTART IDENTITY CASCADE;

-- DROP the tables and constraints
DROP TABLE IF EXISTS pup_services CASCADE;
DROP TABLE IF EXISTS pups CASCADE;


-- CREATE PUPS TABLE
CREATE TABLE IF NOT EXISTS pups (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pup_name TEXT NOT NULL,
    breed TEXT NOT NULL,
    allergies TEXT NOT NULL, 
    hobbies TEXT,
    parent_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

-- insert pups
INSERT INTO pups
  (pup_name, breed, allergies, hobbies)
  VALUES
    ('Cocoa', 'Lab', 'Peanuts', 'Plays Ball'),
    ('Bear', 'Australian Monster', 'Hoomans', 'Protecting my fortress'),
    ('Future', 'Golden RetrievePit', 'Fake people', 'Waiting for crystal to adopt me');


-- CREATE PUPSEVICE table without the foreign key
CREATE TABLE IF NOT EXISTS pup_services (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    appt_date Date,
    service_type TEXT NOT NULL,
    note TEXT,
    pup_id INTEGER REFERENCES pups(id) ON DELETE CASCADE

); 

-- insert values into pup_services
INSERT INTO pup_services
  (appt_date, service_type, note)
  VALUES
    ('12/24/2019', 'Grooming', 'Loves bath time'),
    ('1/14/2020', 'Daycare', 'Hates small dogs'),
    ('2/1/2020', 'Vet', 'Update on shots');


-- Add parent_id to the pups
UPDATE pup_services SET pup_id = 1 WHERE id = 1;
UPDATE pup_services SET pup_id = 2 WHERE id = 2;
UPDATE pup_services SET pup_id = 3 WHERE id = 3;

